### ISSUE TITLE
Incorrect link posted, maybe because my repo has a custom domain

### ISSUE THREAD

**Issue by simonw** [readthedocs/readthedocs-preview#10]
I just tried this out for the first time here:

- https://github.com/simonw/sqlite-utils/pull/460

The preview link it added didn't work, maybe because I have a custom domain setup?

It linked to: https://readthedocs-preview--460.org.readthedocs.build/en/460/ - which 404s

Here's the correct link: https://sqlite-utils--460.org.readthedocs.build/en/460/

My docs are hosted at https://sqlite-utils.datasette.io/ using a custom subdomain setup like this: https://til.simonwillison.net/readthedocs/custom-subdomain

**Comment by stsewd** [comment]
Hi, project slug must be the one of your project

https://github.com/simonw/sqlite-utils/blob/1856002e3c0fcc9f09f72ab7d97ad8c75f6de7df/.github/workflows/documentation-links.yml#L16

that is `sqlite-utils`

**Comment by humitos** [comment]
Hi @simonw! (I'm from the phone). It seems that you didn't change the placeholder for you project's slug. It's using "readthedocs-preview", which is the one from the example.

You have to change that with yours.

Let me know if that helps.

**Comment by simonw** [comment]
Yes, that was the problem! This one worked fine - thanks very much, closing this issue:

- https://github.com/simonw/sqlite-utils/pull/462

**Comment by humitos** [comment]
Thanks @simonw for testing this GH Action! Happy to help with this. Feel free to open any other issue if you find something that's not working as you expect 👍🏼
