### ISSUE TITLE
Support for more than one project

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs-preview#9]
This is the case of our own repo https://github.com/readthedocs/readthedocs.org, where we have the docs and dev projects.

Currently, using the action more than once will override the previous comment

https://github.com/readthedocs/readthedocs-preview/blob/1029696f6a69477ff98e50ddb239e649f86ec384/action.yaml#L51

We should make the comment easier to locate, instead of using a plain `----` as separator, we could use a comment as a delimiter of the start/end of the comment. For example:

```markdown
<!-- rtd-preview {project} start -->
Content
<!-- rtd-preview {project} end -->
```

That way, the current "separator" would be part of the template itself

```markdown
---
:books: Documentation preview :books:: {docs-pr-index-url}
```

**Comment by humitos** [comment]
I liked the idea of using an HTML comment for this! 👍🏼

**Comment by humitos** [comment]
This done in c70557245b0ae077da1a8aeef7f259e88f2916f6

**Comment by humitos** [comment]
I tested it at https://github.com/readthedocs/sphinx-hoverxref/pull/220 and it worked.
